name: Check - TCE Homebrew Formula

on:
  pull_request:
    types:
      - assigned
      - opened
      - synchronize
      - reopened
    paths:
      - "tanzu-community-edition.rb"
      - ".github/workflows/check-tce-homebrew-formula-pr.yaml"

jobs:
  check-tce-homebrew-formula:
    name: Check - TCE Homebrew Formula
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Check - TCE Homebrew Formula
        shell: bash
        run: |
          ./test/check-tce-homebrew-formula.sh
